# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 自动抓取

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: 安装依赖
      run: npm i
    - name: 执行任务
      run: node index.js
    
