# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 测试

on:
 workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
   
    - name: 启动 clash 
      run: docker run -d -p 7890:7890 -p 7891:7891 -p 9090:9090 --name clash dreamacro/clash -v /home/runner/work/clashpool/clashpool/utils/clash/config.yaml:/root/.config/clash/config.yaml -v /home/runner/work/clashpool/clashpool/utils/clash/Country.mmdb:/root/.config/clash/Country.mmdb
    - name: 安装依赖
      run: npm i
    - name: 测试
      run: node test.js
  
