# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 测试

on:
 workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
   
    - name: 赋予权限
      run: |
        chmod +x ./utils/clash
        chmod 755 ./utils/clash
    - name: 测试
      run: node test.js
  
